/**
 * ============================================================
 *  YAHTZEE DB LOADER
 *
 *  Fetches yahtzee_perfect.ydb (generated by generate_db.js)
 *  directly from the project. No building in the browser,
 *  no IndexedDB — the file is always there as a static asset.
 *
 *  File format (binary, little-endian):
 *   bytes  0– 7  : ASCII magic "YTZDB004"
 *   bytes  8–11  : uint32 N_DICE = 252
 *   bytes 12–15  : uint32 N_CATS = 32768
 *   bytes 16–?   : RL0 [252×32768] best catIdx  (rollsLeft=0)
 *   bytes  ?– ?  : RL1 [252×32768] best subsetIdx (rollsLeft=1)
 *   bytes  ?–end : RL2 [252×32768] best subsetIdx (rollsLeft=2)
 * ============================================================
 */

window.YahtzeeDB = (() => {
    'use strict';

    const DB_FILE = 'yahtzee_perfect.ydb';
    const MAGIC = 'YTZDB004';
    const N_CATS = 32768;

    const CAT_LIST = [
        'aces', 'twos', 'threes', 'fours', 'fives', 'sixes',
        'pair', 'two-pairs', 'three-of-a-kind', 'four-of-a-kind', 'full-house',
        'small-straight', 'large-straight', 'yahtzee', 'chance'
    ];

    // ── 252 sorted 5-dice combos ─────────────────────────────
    const DICE_COMBOS = [];
    const DICE_TO_IDX = {};
    (function () {
        (function rec(rem, minV, cur) {
            if (!rem) {
                DICE_TO_IDX[cur.join('')] = DICE_COMBOS.length;
                DICE_COMBOS.push([...cur]); return;
            }
            for (let v = minV; v <= 6; v++) { cur.push(v); rec(rem - 1, v, cur); cur.pop(); }
        })(5, 1, []);
    })();
    const N_DICE = DICE_COMBOS.length; // 252

    // ── Unique multiset subsets per dice combo ────────────────
    const DICE_SUBSETS = DICE_COMBOS.map(dice => {
        const r = [[]];
        (function rec(s, cur) {
            for (let i = s; i < 5; i++) {
                if (i > s && dice[i] === dice[i - 1]) continue;
                cur.push(dice[i]); r.push([...cur]);
                rec(i + 1, cur); cur.pop();
            }
        })(0, []);
        return r;
    });

    // ── Scoring (for rollsLeft=0 results) ────────────────────
    const sm = d => d.reduce((a, b) => a + b, 0);
    const cnt = d => { const c = {}; for (const v of d) c[v] = (c[v] || 0) + 1; return c; };
    const Ov = Object.values.bind(Object);
    const S = {
        aces: d => d.filter(v => v === 1).reduce((a, b) => a + b, 0),
        twos: d => d.filter(v => v === 2).reduce((a, b) => a + b, 0),
        threes: d => d.filter(v => v === 3).reduce((a, b) => a + b, 0),
        fours: d => d.filter(v => v === 4).reduce((a, b) => a + b, 0),
        fives: d => d.filter(v => v === 5).reduce((a, b) => a + b, 0),
        sixes: d => d.filter(v => v === 6).reduce((a, b) => a + b, 0),
        'pair': d => { const c = cnt(d); const p = Object.keys(c).filter(k => c[k] >= 2).map(Number).sort((a, b) => b - a); return p.length > 0 ? p[0] * 2 : 0; },
        'two-pairs': d => {
            const c = cnt(d); const p = Object.keys(c).filter(k => c[k] >= 2).map(Number).sort((a, b) => b - a);
            if (p.length >= 2) return p[0] * 2 + p[1] * 2;
            const f = Object.keys(c).find(k => c[k] >= 4); return f ? parseInt(f) * 4 : 0;
        },
        'three-of-a-kind': d => { const c = cnt(d); const v = Object.keys(c).find(k => c[k] >= 3); return v ? parseInt(v) * 3 : 0; },
        'four-of-a-kind': d => { const c = cnt(d); const v = Object.keys(c).find(k => c[k] >= 4); return v ? parseInt(v) * 4 : 0; },
        'full-house': d => { const v = Ov(cnt(d)).sort(); return (v.length === 2 && v[0] === 2) ? sm(d) : 0; },
        'small-straight': d => { const u = [...new Set(d)].sort((a, b) => a - b).join(''); return ['1234', '2345', '3456'].some(p => u.includes(p)) ? 15 : 0; },
        'large-straight': d => { const u = [...new Set(d)].sort((a, b) => a - b).join(''); return (u === '12345' || u === '23456') ? 20 : 0; },
        'yahtzee': d => new Set(d).size === 1 ? 50 : 0,
        'chance': d => sm(d),
    };

    // ── State ─────────────────────────────────────────────────
    let RL0 = null;  // Uint8Array N_DICE×N_CATS
    let RL1 = null;
    let RL2 = null;
    let _isReady = false;
    let _loadError = null;

    const flat = (di, cm) => di * N_CATS + cm;

    // ── LOAD ──────────────────────────────────────────────────
    async function init() {
        try {
            const res = await fetch(DB_FILE);
            if (!res.ok) {
                _loadError = `HTTP ${res.status} — run "node generate_db.js" first`;
                return false;
            }
            const buf = await res.arrayBuffer();
            const u8 = new Uint8Array(buf);
            const view = new DataView(buf);

            // Validate magic header
            const magic = String.fromCharCode(...u8.slice(0, 8));
            if (magic !== MAGIC) {
                _loadError = 'Invalid or outdated .ydb file (run node generate_db.js)';
                return false;
            }

            const fileDice = view.getUint32(8, true);
            const fileCats = view.getUint32(12, true);
            if (fileDice !== N_DICE || fileCats !== N_CATS) {
                _loadError = `Dimension mismatch in .ydb (got ${fileDice}×${fileCats})`;
                return false;
            }

            const tblSize = N_DICE * N_CATS;
            RL0 = new Uint8Array(buf, 16, tblSize);
            RL1 = new Uint8Array(buf, 16 + tblSize, tblSize);
            RL2 = new Uint8Array(buf, 16 + tblSize * 2, tblSize);

            _isReady = true;
            console.info(`[YahtzeeDB] Loaded ${(buf.byteLength / 1024).toFixed(0)} KB — ${N_DICE}×${N_CATS}×3 states ready`);
            return { entries: N_DICE * N_CATS * 3, fileSizeBytes: buf.byteLength };
        } catch (e) {
            _loadError = e.message;
            return false;
        }
    }

    // ── LOOKUP ────────────────────────────────────────────────
    function lookup(originalDice, availableCats, rollsLeft) {
        if (!_isReady) return null;

        const sorted = [...originalDice].sort((a, b) => a - b);
        const diceIdx = DICE_TO_IDX[sorted.join('')];
        if (diceIdx === undefined) return null;

        const catMask = catsToBitmask(availableCats);
        if (catMask === 0) return null;

        if (rollsLeft === 0) {
            const catIdx = RL0[flat(diceIdx, catMask)];
            const cat = CAT_LIST[catIdx];
            return { action: 'score', category: cat, score: S[cat] ? S[cat](sorted) : 0, fromDB: true };
        }

        const table = rollsLeft === 1 ? RL1 : RL2;
        const subsetIdx = table[flat(diceIdx, catMask)];
        const keepDice = DICE_SUBSETS[diceIdx][subsetIdx] || sorted;

        return {
            action: 'keep',
            keepDice,
            keepIndices: keepToOriginalIndices(originalDice, keepDice),
            rerollCount: 5 - keepDice.length,
            fromDB: true,
        };
    }

    function catsToBitmask(cats) {
        let m = 0;
        for (const c of cats) { const i = CAT_LIST.indexOf(c); if (i >= 0) m |= (1 << i); }
        return m;
    }

    function keepToOriginalIndices(orig, keepVals) {
        const used = new Array(5).fill(false);
        const idx = [];
        for (const v of keepVals) {
            for (let i = 0; i < 5; i++) {
                if (!used[i] && orig[i] === v) { used[i] = true; idx.push(i); break; }
            }
        }
        return idx.sort((a, b) => a - b);
    }

    // ── PUBLIC ────────────────────────────────────────────────
    return {
        init,
        lookup,
        get isReady() { return _isReady; },
        get loadError() { return _loadError; },
        totalStates: N_DICE * N_CATS * 3,
        nDice: N_DICE,
        nCats: N_CATS,
        catList: CAT_LIST,
        // Keep stubs so game.js doesn't break if called
        build: () => { },
        exportToFile: () => alert('DB is a project file — find yahtzee_perfect.ydb in the folder.'),
        importFromFile: () => { },
    };
})();
